# Generated by Django 2.2.6 on 2019-10-04 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iDGame', models.IntegerField()),
                ('vRègles', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.IntegerField(default=0)),
                ('idGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameS.Partie')),
            ],
        ),
    ]
