# Generated by Django 2.2.6 on 2019-10-05 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iDGame', models.IntegerField()),
                ('vRègles', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.IntegerField(default=0)),
                ('idGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameS.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='idGame',
        ),
        migrations.DeleteModel(
            name='Partie',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
