# Generated by Django 2.2.6 on 2019-10-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameS', '0002_auto_20191005_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPlayer', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
            ],
        ),
    ]
